name: build

on:
  workflow_dispatch:

jobs:
  build_job:
    strategy:
      fail-fast: false
    name: jammy_humble
    runs-on: ubuntu-22.04
    steps:
      - uses: jspricke/ros-deb-builder-action@main
        with:
          DEB_DISTRO: jammy
          ROS_DISTRO: humble
          REPOS_FILE: https://raw.githubusercontent.com/tesseract-robotics/tesseract/0.20.2/dependencies.repos
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
          SKIP_ROS_REPOSITORY: true
